# 2015 September 9
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
cache:
  directories:
    - node_modules

# Prepare our tests
# Ensure the project is setup correctly and compiled
install: "npm run-script setup"
before_script: "npm run-script compile"

# Run our tests
script: "npm test"

# Custom notifications
notifications:
  slack:
    secure: ath/YF/bWO5IpdVsYseEec5aMK2SWudls8lHmM6Qp/eVb1l0vyhk/1UWJIULmCGlWURrBnjnxaQmzhAuDGflyTwjgeWHviDfnT/xavn4oUDDYuSKY/6mA5RP344RT5tI5EK0AcQEpHBVKsrmLDtxXSLvCxyS0Y/cuvzJYyQpwAM=
  email:
    recipients:
      secure: yPsw3ZRtKosYOxE/ashjOJ+RsqPNFZxrciVne8cxaQwhHSBNu5x40AZ8AsbKwTk1XHtZZSj+cVj6PNBpvzPsbpLjclzKwuwBTu+3FPSoKAUC6VUudqvtym7gq5xlr+dbH2srDnI2qNckQ6qIbq86oxcvjSdWHcVzCLO2QdLupI4=
