# 2016 April 27
# https://github.com/bevry/base

# Use the latest travis infrastructure
sudo: false

# We use node
language: node_js
node_js:
  #- "0.12"
  #- "4"
  # ^ disabled while flow is busted: https://github.com/facebook/flow/issues/1721#issuecomment-216077420
  - "5"
  - "6"
cache:
  directories:
    - node_modules

# Prepare our tests
# Ensure the project is setup correctly and compiled
install: "npm run-script setup"
before_script: "npm run-script compile"

# Run our tests
script: "npm test"

# Custom notifications
notifications:
  slack:
    secure: lhfe4KMe005dapdKa29BVcLLL3hkTfqTv34GWB7NXELkv3phftGa3c3yNGQJWqxf0TFnR53a/8aMNHTaJlroW7xZNOT1RNnfQgwifdfIGZLf/ARYoFotEPXCU0IlF7gk5qS7vfXw2gwH/qJWw4YS686Ck229LwJ+8QcMageE8eY=
  email:
    recipients:
      secure: c0N+AukbVG94XPAsXZSUYwdZvG+5o++QYABIQyKjLUqV73VKMyE+yu7w3wwdiXREYQ24jmee8kfKjhwgCMQCjlTitUwRHJ0BAPoUAhaJxdj5RqM5O2bDl+pfe1bzvueXEJjEPCyiApsmv1P084isPJzrlE41u7Xwyi8q7OtHc7k=
